# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Capture Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: proxy/build/libs/
    - name: Automatic Releases
      uses: slord399/action-automatic-releases@v1.0.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: false
        title: "自动构建最新版本"
        files: proxy/build/libs/*.*